import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BackupData, exportBackup, readBackup, importBackup } from '../core/backup';
import { UiService } from '../core/ui.service';
import { StorageService } from '../core/storage.service';
import { downloadBlob, formatBytes } from '../core/files';
import { IconComponent } from '../shared/icon.component';
import { DialogComponent } from '../shared/dialog.component';
@Component({selector:'pq-backup',standalone:true,imports:[FormsModule,IconComponent,DialogComponent],template:`
 <div class="backup-grid"><section class="backup-card"><span class="backup-icon"><pq-icon name="download-simple"/></span><h2>A copy, just in case</h2><p>Save your entire workspace as a portable ZIP. Prompts, snippets, commands, tags, order, settings, and every original attachment come with it.</p><button class="button primary" [disabled]="busy()" (click)="export()"><pq-icon name="export"/>{{busy()&&operation()==='export'?'Creating backup…':'Export workspace'}}</button></section><section class="backup-card"><span class="backup-icon import"><pq-icon name="upload-simple"/></span><h2>Pick up where you left off</h2><p>Bring a Prompt Queue backup to this browser. You’ll choose how to import it after the file has been checked.</p><input #picker type="file" accept=".zip,application/zip" hidden (change)="select($event)"><button class="button" [disabled]="busy()" (click)="picker.click()"><pq-icon name="upload-simple"/>{{busy()&&operation()==='read'?'Checking backup…':'Choose a backup'}}</button></section></div>
 <div class="backup-note"><pq-icon name="shield"/><div><strong>Your backup belongs to you.</strong><p>Files are created and read on this device. Backups are not encrypted; store them somewhere you trust. Browser data can be cleared or evicted, so export regularly.</p></div></div>
 @if(pending()){<pq-dialog heading="Restore your workspace" [busy]="busy()" (dismiss)="pending.set(null)"><p class="muted">The backup is valid. Choose how to bring it into this workspace.</p><div class="backup-file"><pq-icon name="archive"/><span>{{filename()}}<small>{{size(fileSize())}}</small></span></div><label class="import-option"><input type="radio" name="mode" value="merge" [(ngModel)]="mode"><span><strong>Merge into this workspace</strong><small>Keep everything here and add the backup as new items. Importing the same backup again creates another copy.</small></span></label><label class="import-option"><input type="radio" name="mode" value="replace" [(ngModel)]="mode"><span><strong>Replace this workspace</strong><small>Delete current prompts, snippets, commands, and attachments, then restore the backup and its settings.</small></span></label>@if(mode==='replace'){<label class="replace-check"><input type="checkbox" [(ngModel)]="replaceConfirmed"><span>I understand this permanently replaces all current data.</span></label>}
 @if(error()){<p class="inline-error" role="alert">{{error()}}</p>}<footer class="dialog-actions"><button class="button" [disabled]="busy()" (click)="pending.set(null)">Cancel</button><button class="button primary" [disabled]="busy() || (mode==='replace'&&!replaceConfirmed)" (click)="restore()">{{busy()?'Importing…':mode==='merge'?'Merge backup':'Replace workspace'}}</button></footer></pq-dialog>}
 `,styles:`.backup-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.backup-card{padding:32px;border:1px solid var(--border);border-radius:12px;background:var(--surface);display:flex;align-items:flex-start;flex-direction:column}.backup-icon{display:grid;place-items:center;width:52px;height:52px;border-radius:12px;background:#e8eee2;margin-bottom:22px}.backup-icon.import{background:#eee6dc}.backup-icon pq-icon{width:27px;height:27px}h2{font-size:23px;font-weight:500;margin:0 0 13px}p{font-size:13px;color:var(--muted);line-height:1.7;margin:0 0 25px}.backup-card .button{margin-top:auto}.backup-note{display:flex;gap:15px;margin-top:24px;padding:23px;background:var(--soft);border-radius:10px}.backup-note strong{font-size:13px;font-weight:500}.backup-note p{font-size:12px;margin:7px 0 0}.backup-file{display:flex;align-items:center;gap:14px;padding:15px;background:var(--soft);border-radius:9px;margin:20px 0}.backup-file span{font-size:13px;overflow-wrap:anywhere}.backup-file small{display:block;margin-top:5px;color:var(--muted)}.import-option{display:flex;align-items:flex-start;gap:13px;padding:16px;border:1px solid var(--border);border-radius:9px;margin-top:10px;cursor:pointer}.import-option input{margin-top:3px}.import-option strong{font-size:13px;font-weight:500}.import-option small{display:block;font-size:12px;line-height:1.5;color:var(--muted);margin-top:7px}.replace-check{display:flex;gap:10px;align-items:flex-start;font-size:12px;color:var(--danger);margin-top:18px}@media(max-width:680px){.backup-grid{grid-template-columns:1fr}.backup-card{padding:24px}}`})
export class BackupComponent {
  ui=inject(UiService);storage=inject(StorageService);busy=signal(false);error=signal('');operation=signal('');pending=signal<BackupData|null>(null);filename=signal('');fileSize=signal(0);size=formatBytes;mode:'merge'|'replace'='merge';replaceConfirmed=false;
  async export():Promise<void>{this.busy.set(true);this.operation.set('export');await this.ui.run(async()=>{const blob=await exportBackup(this.ui.settings());downloadBlob(blob,`prompt-queue-${new Date().toISOString().slice(0,10)}.zip`);},'Backup downloaded');this.busy.set(false);}
  async select(event:Event):Promise<void>{const input=event.target as HTMLInputElement;const file=input.files?.[0];input.value='';if(!file)return;this.busy.set(true);this.operation.set('read');await this.ui.run(async()=>{this.pending.set(await readBackup(file));this.filename.set(file.name);this.fileSize.set(file.size);this.mode='merge';this.replaceConfirmed=false;this.error.set('');});this.busy.set(false);}
  async restore():Promise<void>{const data=this.pending();if(!data||this.busy()||(this.mode==='replace'&&!this.replaceConfirmed))return;this.busy.set(true);this.error.set('');this.operation.set('import');try{const settings=await importBackup(data,this.mode);if(settings)this.ui.setSettings({showQuickPrompts:true,showSnippets:true,showCommands:true,showStorage:true,...settings});await this.storage.refresh();this.pending.set(null);this.ui.notify('Backup imported successfully');}catch(error){this.error.set(error instanceof Error?error.message:'The backup could not be imported. Your existing data has been kept.');}finally{this.busy.set(false);}}
}
