import { Component, inject, input, output } from '@angular/core';
import { LibraryItem, LibraryKind } from '../core/models';
import { ClipboardService } from '../core/clipboard.service';
import { IconComponent } from '../shared/icon.component';
@Component({selector:'pq-library',standalone:true,imports:[IconComponent],template:`
 <section class="library-panel" [class.full]="full()" [class.snippets]="kind()==='snippets'" [class.commands]="kind()==='commands'" [attr.aria-label]="heading()">
   @if(!full()){<header><h2>{{heading()}}</h2><button class="text-button" (click)="viewAll.emit()">View all</button></header>}
   <div class="library-list">@for(item of items();track item.id;let i=$index){<article class="library-item"><button class="library-main" (click)="edit.emit(item)" [attr.aria-label]="'Edit '+item.title"><span class="library-icon" [class]="'library-icon color-'+(kind()==='snippets'?'neutral':i%8)"><pq-icon [name]="item.icon"/></span><span class="library-text"><strong>{{item.title}}</strong><span class="library-preview">{{item.body}}</span></span></button><button class="icon-button copy-button" [attr.aria-label]="'Copy '+item.title" title="Copy full text" (click)="clipboard.copy(item.body)"><pq-icon name="copy"/></button>@if(full()){<button class="icon-button" [attr.aria-label]="'Edit '+item.title" (click)="edit.emit(item)"><pq-icon name="pencil-simple"/></button><button class="icon-button danger" [attr.aria-label]="'Delete '+item.title" (click)="remove.emit(item)"><pq-icon name="trash"/></button>}</article>}
   @empty{<div class="small-empty">{{emptyText()}}</div>}</div>
 </section>`,styles:`.library-panel{border:1px solid var(--border);border-radius:11px;background:var(--surface);padding:20px 20px 17px}header{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}h2{font-size:21px;letter-spacing:-.8px;margin:0;font-weight:500}.library-list{display:grid;gap:10px}.library-item{display:flex;gap:8px;align-items:center;min-width:0}.library-main{display:flex;align-items:center;gap:16px;flex:1;min-width:0;text-align:left;border-radius:7px}.library-main:hover .library-text strong{color:var(--brown)}.library-icon{height:44px;width:44px;display:grid;place-items:center;border-radius:9px;flex-shrink:0}.library-icon pq-icon{width:24px;height:24px}.color-0,.color-6{background:#e6d8ff}.color-1{background:#d5e9d9}.color-2{background:#ffcbbb}.color-3{background:#c9ddff}.color-4{background:#ffe2ba}.color-5{background:#c9e7e1}.color-7{background:#e2eeff}.color-neutral{background:var(--soft)}.library-text{display:grid;gap:3px;min-width:0}.library-text strong{font-size:13px;font-weight:500;letter-spacing:-.25px}.library-preview{font-size:12px;color:var(--muted);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.copy-button{height:30px;width:27px;flex-shrink:0}.copy-button pq-icon{width:18px;height:18px}.snippets .library-icon{width:36px;height:38px}.snippets .library-icon pq-icon{width:22px;height:22px}.snippets .library-list{gap:14px}.snippets .library-main{gap:13px}.snippets header{margin-bottom:18px}.snippets .library-preview{font-size:11px}.full{padding:8px 24px}.full .library-list{gap:0}.full .library-item{padding:18px 0;border-bottom:1px solid var(--border)}.full .library-item:last-child{border-bottom:0}.full .library-text strong{font-size:15px}.full .library-preview{font-size:13px}.full .library-icon{width:45px;height:45px}.commands .library-preview{font-family:monospace}.small-empty{padding:24px 0;text-align:center;font-size:13px;color:var(--muted)}`})
export class LibraryComponent {
  items=input.required<LibraryItem[]>();kind=input<LibraryKind>('quickPrompts');full=input(false);emptyText=input('Nothing here yet. Create your first one.');edit=output<LibraryItem>();remove=output<LibraryItem>();viewAll=output<void>();clipboard=inject(ClipboardService);
  heading():string{return this.kind()==='commands'?'Commands':this.kind()==='snippets'?'Snippets':'Quick prompts';}
}
