import { Component, input, output, inject } from '@angular/core';
import { DatePipe } from '@angular/common';
import { CdkDrag, CdkDragHandle } from '@angular/cdk/drag-drop';
import { Prompt, Attachment } from '../core/models';
import { ClipboardService } from '../core/clipboard.service';
import { IconComponent } from '../shared/icon.component';
import { AttachmentComponent } from '../shared/attachment.component';
@Component({selector:'pq-prompt-card',standalone:true,imports:[DatePipe,CdkDragHandle,IconComponent,AttachmentComponent],hostDirectives:[{directive:CdkDrag,inputs:['cdkDragDisabled']}],template:`
 <article class="prompt-card" [class.archived]="archived()">
   @if(!archived()){<div class="reorder-controls"><button cdkDragHandle class="drag-handle icon-button" [disabled]="!reorderEnabled()" [attr.aria-label]="'Reorder '+prompt().title+'. Use arrow keys to move.'" (keydown.arrowup)="moveByKey($event,-1)" (keydown.arrowdown)="moveByKey($event,1)"><pq-icon name="dots-six-vertical"/></button><span class="position">{{index()+1}}</span></div>}
   <div class="prompt-content">
     <div class="card-heading"><button class="title-button" (click)="edit.emit(prompt())"><h2>{{prompt().title}}</h2></button><time [attr.datetime]="iso()">{{prompt().updatedAt | date:'MMM d, HH:mm'}}</time>
       <div class="card-actions"><button class="icon-button" [attr.aria-label]="'Copy '+prompt().title" title="Copy full prompt" (click)="clipboard.copy(prompt().body)"><pq-icon name="copy"/></button>
         @if(archived()){<button class="icon-button" title="Restore to queue" aria-label="Restore to queue" (click)="restore.emit(prompt())"><pq-icon name="arrow-counter-clockwise"/></button><button class="icon-button danger" title="Permanently delete" aria-label="Permanently delete prompt" (click)="remove.emit(prompt())"><pq-icon name="trash"/></button>}
         @else{<button class="icon-button" [attr.aria-label]="'Edit '+prompt().title" title="Edit prompt" (click)="edit.emit(prompt())"><pq-icon name="pencil-simple"/></button><button class="icon-button" [attr.aria-label]="'Archive '+prompt().title" title="Archive prompt" (click)="archive.emit(prompt())"><pq-icon name="archive"/></button>}
       </div>
     </div>
     <p class="body-preview">{{prompt().body}}</p>
     <div class="attachments-row">@for(attachment of attachments();track attachment.id){<pq-attachment [attachment]="attachment" (open)="openAttachment.emit($event)"/>}@if(!archived()){<button class="add-attachment" title="Add attachments" aria-label="Add attachments" (click)="edit.emit(prompt())"><pq-icon name="plus"/></button>}</div>
     <div class="tags-row">@for(tag of prompt().tags;track tag){<button class="tag" (click)="searchTag.emit(tag)">{{tag}}</button>}@if(!archived()){<button class="tag add-tag" aria-label="Edit tags" title="Edit tags" (click)="edit.emit(prompt())"><pq-icon name="plus"/></button>}</div>
   </div>
 </article>`,styles:`:host{display:block}.prompt-card{display:flex;gap:22px;padding:17px 18px 16px 12px;background:var(--surface);border:1px solid var(--border);border-radius:11px;transition:border-color .15s,box-shadow .15s}.prompt-card:hover{border-color:var(--card-hover-border,#dfd4cb);box-shadow:0 3px 14px #6b514804}.reorder-controls{display:flex;align-self:flex-start;align-items:flex-start;gap:10px;padding-top:0}.drag-handle{width:20px;margin-top:6px;cursor:grab;color:var(--muted);touch-action:none}.drag-handle:active{cursor:grabbing}.position{display:grid;place-items:center;width:41px;height:41px;border-radius:50%;background:var(--soft);font:500 21px 'Lora',Georgia,serif}.prompt-content{min-width:0;flex:1}.card-heading{display:flex;gap:10px;align-items:center;min-height:29px}.title-button{text-align:left;min-width:0;flex:1}.title-button h2{font-size:18px;line-height:1.45;letter-spacing:-.65px;margin:0;font-weight:500}.title-button:hover h2{color:var(--brown)}time{color:var(--muted);white-space:nowrap;font-size:11px}.card-actions{display:flex;gap:9px;margin-left:8px}.card-actions .icon-button{width:28px;height:29px}.card-actions pq-icon{width:19px;height:19px}.body-preview{font-size:13px;color:var(--muted);line-height:1.42;margin:5px 65px 10px 0;white-space:pre-wrap;overflow-wrap:anywhere;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.attachments-row{display:flex;align-items:center;flex-wrap:wrap;gap:7px}.add-attachment{height:52px;width:49px;display:grid;place-items:center;background:var(--soft);color:var(--brown);border-radius:7px}.add-attachment:hover{background:var(--selected)}.add-attachment pq-icon{opacity:.5}.tags-row{display:flex;flex-wrap:wrap;gap:10px;margin-top:12px}.add-tag{padding:0;width:29px;height:29px;display:grid;place-items:center}.add-tag pq-icon{width:15px;height:15px}.archived{padding-left:24px}:host-context(.compact) .prompt-card{padding-top:13px;padding-bottom:13px}:host-context(.compact) .body-preview{-webkit-line-clamp:1}:host-context(.compact) .attachments-row pq-attachment{display:none}@media(max-width:1200px){time{display:none}.prompt-card{gap:14px}.card-actions{gap:3px}}@media(max-width:680px){.prompt-card{gap:10px;padding:16px 12px}.reorder-controls{flex-direction:column-reverse;gap:3px;align-items:center}.position{width:30px;height:30px;font-size:16px}.title-button h2{font-size:16px}.card-actions{gap:0}.card-actions .icon-button{width:27px}.body-preview{margin-right:0}.card-heading{align-items:flex-start}.attachments-row{gap:6px}}`})
export class PromptCardComponent {
  prompt=input.required<Prompt>();index=input(0);attachments=input<Attachment[]>([]);archived=input(false);reorderEnabled=input(true);
  edit=output<Prompt>();archive=output<Prompt>();restore=output<Prompt>();remove=output<Prompt>();openAttachment=output<Attachment>();searchTag=output<string>();move=output<number>();clipboard=inject(ClipboardService);
  iso():string{return new Date(this.prompt().updatedAt).toISOString();}
  moveByKey(event:Event,offset:number):void{event.preventDefault();if(this.reorderEnabled())this.move.emit(offset);}
}
