import { Component, inject } from '@angular/core';
import { UiService } from '../core/ui.service';
import { StorageService } from '../core/storage.service';
import { IconComponent } from '../shared/icon.component';
import { StoragePanelComponent } from './storage-panel.component';
@Component({selector:'pq-settings',standalone:true,imports:[IconComponent,StoragePanelComponent],template:`
 <section class="settings-card"><h2>Make yourself at home</h2><p class="muted">A few small preferences for your workspace.</p><div class="setting-row"><div><h3>Queue density</h3><p>Choose how much room your prompts have.</p></div><div class="segmented" role="group" aria-label="Queue density"><button [class.active]="ui.settings().density==='comfortable'" [attr.aria-pressed]="ui.settings().density==='comfortable'" (click)="ui.setSettings({density:'comfortable'})">Comfortable</button><button [class.active]="ui.settings().density==='compact'" [attr.aria-pressed]="ui.settings().density==='compact'" (click)="ui.setSettings({density:'compact'})">Compact</button></div></div><div class="setting-row"><div><h3>Appearance</h3><p>A warm, quiet place to think.</p></div><span class="theme-label"><pq-icon name="sun"/>Warm light</span></div></section>
 <section class="settings-card"><h2>A little extra peace of mind</h2><div class="setting-row"><div><h3>Persistent storage</h3><p>{{storage.persisted()===true?'Granted — your browser protects this origin from automatic storage eviction.':storage.persisted()===false?'Not granted. Request protection from automatic browser storage eviction.':'Your browser has not reported its persistence status.'}}</p><p class="helper">Clearing site data still removes your prompts. Keep a backup of anything important.</p></div><button class="button" [disabled]="storage.persisted()===true || storage.checking()" (click)="requestPersistence()"><pq-icon name="shield"/>{{storage.persisted()?'Granted':storage.checking()?'Requesting…':'Protect local data'}}</button></div><pq-storage-panel/></section>
 <section class="settings-card about"><pq-icon name="stack"/><div><h3>Prompt Queue <span>v0.1.0</span></h3><p>A local staging area for your next good idea. No accounts, AI connections, analytics, or cloud syncing.</p></div></section>`,styles:`:host{display:grid;gap:18px}.settings-card{padding:26px;background:var(--surface);border:1px solid var(--border);border-radius:11px}h2{font-size:22px;font-weight:500;margin:0 0 9px}h3{font:500 14px var(--font-body);margin:0 0 7px}p{font-size:13px;margin:0;color:var(--muted);line-height:1.6}.setting-row{display:flex;align-items:center;justify-content:space-between;gap:30px;padding:24px 0;border-bottom:1px solid var(--border)}.setting-row:last-child{border-bottom:0;padding-bottom:0}.segmented{display:flex;background:var(--soft);padding:4px;border-radius:8px;flex-shrink:0}.segmented button{font-size:12px;padding:9px 12px;border-radius:5px;color:var(--muted)}.segmented button.active{background:var(--surface);color:var(--brown);box-shadow:0 1px 5px #38251b0d}.theme-label{display:flex;gap:8px;align-items:center;font-size:13px;white-space:nowrap}.setting-row>.button{flex-shrink:0}.helper{margin-top:8px;font-size:12px}.about{display:flex;gap:18px;align-items:center}.about>pq-icon{width:30px;height:30px}.about h3 span{font-weight:400;color:var(--muted);font-size:11px;margin-left:7px}pq-storage-panel{display:block;margin-top:22px}@media(max-width:680px){.setting-row{align-items:flex-start;flex-direction:column;gap:16px}.settings-card{padding:20px}}`})
export class SettingsComponent {
  ui=inject(UiService);storage=inject(StorageService);
  async requestPersistence():Promise<void>{await this.ui.run(async()=>{const value=await this.storage.requestPersistence();this.ui.notify(value===null?'Persistent storage is unavailable in this browser.':value?'Persistent storage granted.':'The browser did not grant persistence. You can still use the app and export backups.');});}
}
